### ISSUE TITLE
Query about test configuration

### ISSUE THREAD

**Issue by wanderingcar** [rpl-cmu/risam#1]
Hi,

Firstly, I really appreciate the effort and dedication you've put into developing and sharing this great work.

I've been testing RISAM alongside your paper, but I'm not getting the metrics presented in the paper for the sphere2500 dataset, especially the "recall" metric. I followed the guidance written on the README.md inside the experiments folder:
`./scripts/g2o-2-irl -i datasets/sphere2500/sphere2500.g2o -n sphere2500 -o ~/risam_test_environment/datasets/ --is3d --add_outliers --outlier_percentiles 10 --outlier_covariance 0.1 0.1 0.1 0.0025 0.0025 0.001 --outlier_chi2_thresh 0.95`

I used the covariance value from the g2o file.

If you don't mind, can you share the configuration you used for your paper?

Thanks in advance!

**Comment by DanMcGann** [comment]
Because of how long prior works too to run on this dataset only a single trial was run. There is a chance that the random seed generated a "lucky" dataset for the riSAM parameters evaluated in the paper. I generated a few extra datasets today and am also seeing slightly lower recall than on the dataset used for paper experiments.

One thing to note is that for consistency we used the same parameters for all experiments in the paper. However, for 3d datasets the SIG-Kernel shape parameter should be increased given the larger dimensional of the measurements (shape parameter is a residual which are [chi2 distributed](https://en.wikipedia.org/wiki/Chi-squared_distribution)). I ran with a higher shape parameter value (`c=6` though the theoretically correct value is `c=12` for 95% confidence) on the datasets I generated today and as expected observe more stable results that are inline with the expected performance.
