### ISSUE TITLE
How to implement outlier estimation in prior factors

### ISSUE THREAD

**Issue by qian5683** [rpl-cmu/risam#2]
Thank you for your outstanding work, but I have some questions that I hope you can help answer：
I have some GPS observations similar to prior factors, but these GPS observations have outliers. How can I modify the code to implement outlier estimation for prior factors？

**Comment by DanMcGann** [comment]
Great Question!

The class `GenericGraduatedFactor` provides everything you need to use GNC with an arbitrary factor (including GPS factors), and example of how this is used in the riSAM experiments can be found here:

https://github.com/rpl-cmu/risam/blob/a6f9b4459e6820f81f6d2d113d57d43638ae32a3/experiments/irl/include/irl/irl_types-inl.h#L280-L289

The key idea is that `risam:make_shared_graduated<T>` functions like `boost::make_shared<T>` in that it forwards arguments to the factor type `T` but in the case of the `make_shared_graduated` you also provide it with a graduated kernel and it wraps the factor in a Generic Graduated Factor so that riSAM can linearize it according to $\mu$ correctly.

The only other thing you need to do is to set the flag `known_inliers` to false when calling `risam::RISAM2::update` or else the factors will always be linearized according to a quadratic cost.

Putting this together we end up with the following minimal example.

```
// Note ensure to set parameters as defined in in Factory.h
risam::RISAM2 risam(risam::RISAM2::RISAM2Params());
gtsam::NonlinearFactorGraph fg;
gtsam::Values init_vals;

fg.push_back(risam::make_shared_graduated<gtsam::GPSFactor>(boost::make_shared<risam::SIGKernel>(3), X(0), gtsam::Point3(0,0,0), gtsam::noiseModel::Isotropic::Sigma(3, 0.1)); # c=3 for 3 dim factor
init_vals.push_back(gtsam::Pose3());

solver->update(fg, init_vals, false);
```

Note: I have not run the code snippet above, so there may be typos, but it should be instructive on how to use riSAM with outlier GPS measurements. If you run into trouble open this issue again we can discuss further, or I can put together a mininal example script.
